" Fixes some things when I used fish
set shell=/bin/bash

execute pathogen#infect()

" to make lightline.vim show and for colors
set laststatus=2
if !has('gui_running')
	set t_Co=256
endif

colorscheme elflord

" Mode displayed by lightline
set noshowmode

let g:promptline_preset = {
	\'a' : [ promptline#slices#host() ],
	\'b' : [ promptline#slices#user() ],
	\'c' : [ promptline#slices#cwd() ],
	\'y' : [ promptline#slices#vcs_branch() ],
	\'warn' : [ promptline#slices#last_exit_code() ]}

" Configure lightline
let g:lightline = {
	\ 'colorscheme': 'wombat',
	\ 'component': {
	\   'readonly': '%{&readonly?"":""}',
	\ },
	\ 'separator': { 'left': '', 'right': '' },
	\ 'subseparator': { 'left': '', 'right': '' },
	\ }

" Vim can recognize files and can load plugins
filetype on
filetype plugin on

" pretty much always want Syntax highlighting
syntax on

nnoremap <F7> :setlocal spell!<CR>
set dictionary=/usr/share/dict/words

" For autocompletion
set completeopt=noinsert,menuone
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
inoremap <expr> <Down> pumvisible() ? "\<C-n>" : "\<Down>"
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <Up> pumvisible() ? "\<C-p>" : "\<Up>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <C-n> pumvisible() ? '<C-n>' :
  \ '<C-n><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'
inoremap <expr> <C-Space> <C-x><C-o>
imap <C-@> <C-Space>

set ignorecase
set hlsearch
set incsearch
set showcmd
set wildmenu
set nowrap
filetype indent on
set autoindent noexpandtab tabstop=4 shiftwidth=4
set nolazyredraw
set ttyfast

" Highlight the current line
set cursorline
hi CursorLine term=bold cterm=bold ctermbg=236

" Mark column limit and force new line when typing past
set tw=80
set cc=80
hi ColorColumn ctermbg=240
set nojoinspaces

" If we were using X11, this would use its clipboard. Vim needs to be compiled
" with X11 and xterm_clipboard for this to work. see :version
set clipboard=unnamedplus

" send deleted and changed text to black hole register
nnoremap d "_d
nnoremap D "_D
vnoremap d "_d
vnoremap D "_D

nnoremap C "_C
vnoremap C "_C

" Template files
autocmd BufNewFile *.c 0r ~/.vim/templates/template.c
autocmd BufNewFile *.py 0r ~/.vim/templates/template.py
autocmd BufNewFile *.sh 0r ~/.vim/templates/template.sh

" Invisible characters
" use "set list" to turn on and "set nolist" to turn off
set listchars=eol:¬,tab:»\ ,space:·

" Set the swap and backup dir to something not annoying
set directory=~/.vim/.swp,/tmp
set backupdir=~/.vim/.backup,/tmp

" I don't want mouse
set mouse=
set ttymouse=
